### ISSUE TITLE
The plugin could read your API key and settings from the global WakaTime config

### ISSUE THREAD

**Issue by danglingptr0x0** [thomazthz/godot-wakatime#3]
Hello,

Most of WakaTime's plugins for IDEs and editors share a config located in ~/.wakatime.cfg, where the API key is located.

Accessing this instead of writing a new one would make things a bit easier—just a recommendation.

Have a nice day!

**Comment by 201flaviosilva** [comment]
Hey there,
I would like too, the plugin to be global, as it is for example in VS Code :)

**Comment by Snailedlt** [comment]
+1

**Comment by thomazthz** [comment]
Hey! (ʘ‿ʘ)╯

The Godot WakaTime plugin now uses the WakaTime global configuration file (`$WAKATIME_HOME/.wakatime.cfg`). It was added in [v1.5.0](https://github.com/thomazthz/godot-wakatime/releases/tag/v1.5.0) along with Godot 4.X support. 

However, older versions of the plugin still use a local configuration file.

**Comment by danglingptr0x0** [comment]
> Hey! (ʘ‿ʘ)╯
> 
> The Godot WakaTime plugin now uses the WakaTime global configuration file (`$WAKATIME_HOME/.wakatime.cfg`). It was added in [v1.5.0](https://github.com/thomazthz/godot-wakatime/releases/tag/v1.5.0) along with Godot 4.X support.
> 
> However, older versions of the plugin still use a local configuration file.

Hi!

Much appreciated :-)

Have a nice day
