### ISSUE TITLE
[Windows] Plugin do not see Python even if it is actually installed.

### ISSUE THREAD

**Issue by elenakrittik** [thomazthz/godot-wakatime#4]
I have Python installed, and it is in my PATH.

Output:
```
 Python not found! Install Python from https://www.python.org/downloads/ and reload godot-wakatime plugin
 Disconnecting nonexistent signal 'editor_script_changed', slot: 42211:_on_script_changed.
 core/object.cpp:1442 - Parameter "p_to_object" is null.
```

Python version: 3.10.2
Godot version: 3.4.4
Plugin version: 1.3.5
Plugin installation source: Asset Library
OS: Windows 10 64-bit

Note: extracting embeddable Python into `addons/wakatime` did not help.

**Comment by alanhamlett** [comment]
Let's upgrade to the new wakatime-cli which doesn't need Python.

**Comment by elenakrittik** [comment]
As a some sort of workaround, I'm currently using Steam version of Godot.

**Comment by thomazthz** [comment]
As suggested by @alanhamlett , I just removed the Python dependency and updated the wakatime-cli.

@ItsAleph I believe the new plugin version (v1.4.0) should work in your setup. I just submitted to Godot asset library and should be available soon. But you can also download from releases page https://github.com/thomazthz/godot-wakatime/releases/tag/v1.4.0

**Comment by elenakrittik** [comment]
Sadly, i uninstalled windows a few weeks ago and only have Kubuntu for games and Manjaro for deving, so i cannot test it rn, but it works on Manjaro at least. Hope someone else on windows can get hands to test this :(

**Comment by thomazthz** [comment]
The [v1.4.0](https://github.com/thomazthz/godot-wakatime/releases/tag/v1.4.0) now works with Godot `>=3.3.X,<4.X` on Windows and Linux :relaxed: It is already published in the [Godot Asset Library](https://godotengine.org/asset-library/asset/236)
