### ISSUE TITLE
Unable to load on Godot 4 alpha

### ISSUE THREAD

**Issue by exoego** [thomazthz/godot-wakatime#5]
Hello, thanks for this plugin.

During my trial on Godot 4 alpha, I saw `godot-wakatime` was not loaded.
`godot-waktime` worked perfectly on my Godot 3.4 projects, so I guess this is due to some breaking changes in Godot 4.
I hope `godot-wakatime` adds support to Godot 4.

## Steps
1. [Get Godot 4 alpha11 build](https://downloads.tuxfamily.org/godotengine/4.0/alpha11/) and install
2. New project in Godot
3. [Get godot-wakatime](https://github.com/thomazthz/godot-wakatime/releases/tag/v1.3.5) and uncompress.
4. Import the `wakatime` folder in `godot-waktime` into `addon` folder in Godot project
5. `Project > Project Settings > Plugins`
6. Click `Enable`
7. Error message `Unable to load addon script from path: 'res://addons/wakatime/wakatime.gd'. This might be due to a code error in that script. Disabling the addon at 'res://addons/wakatime/plugin.cfg' to prevent further errors.` is shown.

## environment
- Python version: 3.8.12
- Godot version: 4.0.alpha11
- Plugin version: 1.3.5
- Plugin installation source: GitHub
- OS: macOS 12.4

**Comment by thomazthz** [comment]
Hello (ʘ‿ʘ)╯

Support for Godot 4.X was just added in Godot WakaTime [v1.5.0](https://github.com/thomazthz/godot-wakatime/releases/tag/v1.5.0).

https://godotengine.org/asset-library/asset/236
